apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-ec2
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "eksctl-KarpenterNodeRole-karpenter-lab-eks"
  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/karpenter-lab-eks: shared
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/karpenter-lab-eks: shared
  tags:
    Name: "karpenter-lab-eks-node"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        node.kubernetes.io/lifecycle: karpenter
        workload: general
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-ec2
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.medium", "t3.large", "t3.xlarge", "t3.2xlarge"]
  limits:
    cpu: "64"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
