apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-proj
  namespace: argocd
spec:
  description: "Demo project"
  sourceRepos:
    - '*'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
