cni:
  chainingMode: aws-cni
  exclusive: false

routingMode: native
enableIPv4Masquerade: false
kubeProxyReplacement: false

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

# Envoy as DaemonSet (node-wide)
envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

# Hubble + Flow Export
hubble:
  enabled: true
  relay:
    enabled: false
  ui:
    enabled: false
  export:
    static:
      enabled: true
      filePath: /var/run/cilium/hubble/events.log
  metrics:
    enableOpenMetrics: true
    enabled:
      - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
