name: Deploy AWS Backend (Serverless Framework)

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - '.github/workflows/aws-deploy-be.yaml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install Serverless Framework v3
              run: npm install -g serverless@3.40.0

            - name: Install Serverless plugin dependencies
              run: npm install -g serverless-esbuild serverless-prune-plugin

            - name: Install TypeScript
              run: |
                cd backend
                npm install typescript ts-node @types/node --save-dev

            - name: Install project dependencies
              run: |
                cd backend
                npm install

            - name: Build TypeScript files
              run: |
                cd backend
                tsc

            - name: Deploy with Serverless Framework
              run: |
                cd backend
                npx serverless deploy --verbose
              env:
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
