apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-svc
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      nodePort: 30001
