apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
        - name: myapp
          image: rlawnsdud/demo
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5678"
            - name: APP_NAME
              value: "myapp v1"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-v1
spec:
  selector:
    app: myapp
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: v2
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
        - name: myapp
          image: rlawnsdud/demo
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5678"
            - name: APP_NAME
              value: "myapp v2"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-v2
spec:
  selector:
    app: myapp
    version: v2
  ports:
    - name: http
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otherapp
  template:
    metadata:
      labels:
        app: otherapp
    spec:
      containers:
        - name: otherapp
          image: rlawnsdud/demo
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5678"
            - name: APP_NAME
              value: "otherapp"
            - name: GLOBAL_PREFIX
              value: "/other"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: otherapp
spec:
  selector:
    app: otherapp
  ports:
    - name: http
      port: 80
      targetPort: 5678
