apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-gwapi
spec:
  profile: default
  meshConfig:
    enableTracing: false
    accessLogFile: /dev/stdout
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        enabled: true
    pilot:
      env:
        PILOT_ENABLE_GATEWAY_API: "true"
