apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
  labels: { app: example-app }
spec:
  replicas: 1
  selector:
    matchLabels: { app: example-app }
  template:
    metadata:
      labels: { app: example-app }
    spec:
      containers:
        - name: app
          image: rlawnsdud/demo:arm
          ports:
            - containerPort: 8080
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: default
  labels: { app: example-app }
spec:
  selector: { app: example-app }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
