global:
  rbac:
    create: true

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
          # storageClassName: gp2
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    probeSelector: {}
    probeNamespaceSelector: {}
    scrapeConfigSelector: {}
    scrapeConfigNamespaceSelector: {}

alertmanager:
  alertmanagerSpec:
    replicas: 1

grafana:
  adminUser: admin
  service:
    type: ClusterIP
  defaultDashboardsEnabled: true

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true
